### PR TITLE
Personalised recommendations, member exclusives, Menu & customising ingredient features with takeaway modal

### LINKED ISSUE #7: Menu display
## Description
The menu consists of a 4-step sandwich and 5-step smoothie customisations, where flexibility is offered to choose from ingredients and fruits to add to a delicious meal. There are also stevia levels in consideration to provide a healthier smoothie for customers accounting for their health goals. 

## User Story
As a customer, I want to see what are the items recommended to me based on my visits with the sandwich outlet. I want to be able to see what are the promotional products i can enjoy along with variety of ingredients to opt for a delicious smoothie and sandwich.

## Acceptance Criteria
A clear and concise description of requirements so that when all of them are fulfilled, The issue is considered complete and can be closed.
- [x] Easy to navigate
- [x] Descriptions and prices
- [ ] Special promotion and featured items

## Notes
image
image
image

### PR DESCRIPTION
**Pull request by jumanahaseenn**
## Purpose
Purpose of the Pull Request is to check menu feature works where users can customise sandwich and smoothie for takeaway.

## Description of Changes
- "Home" navigation in menu correctly displays personalised items including member exclusive drink for existing customers based on their frequent purchase. (ps: this section wont appear for newly registered customers, havent work on it yet)
- Check sandwich and smoothie customisation process by clicking individual icons. To review whether all 4 steps in sandwich making and 5 steps in DIY smoothie blending works smoothly and an order display summary is shown at the end.

- Upon clicking the "Complete" button in Order summary, there should be a pop up of takeaway. this is temporary till "Adding to cart" feature is implemented. 

Kindly review all the items mentioned above.

Upcoming changes for next review:
- Prices will be added soonn
- Cart will be created where customers can claim rewards and discounts
- Takeaway modal will be fixed with a correct location featured.

Thanks!

## Feedback Requested
Review of changes. 

## Testing Performed
Ran code locally.

## People to Notify
@User1

## Checklist

- [ ] Unit tests written.
- [x] Feature or bug is completed.
- [x] Code is readable, comments and doc string written.
- [x] Code style follows PEP 8 conventions.
- [x] Built and tested on Docker.
- [x] Updated `requirements.txt`.
- [x] Conflicts with base branch resolved.

### CODE REVIEW

**Comment by yyingxuann** [comment]
**UI/UX**
- Is it possible to have the entire page stay within the web dimensions? Current moment, the page has a horizontal scrollwheel. (see arrow)
image
- Start of all words should be capitalised in the header (Customise Your Meal)
image
- Split into two lines, maybe increase the font size and use lesser words for the food's main description (same for smoothie) -- can reference the way you did the Promotions 
image

**Both Sandwich & Smoothie**
- Next step button should always be on the right, especially step 1 - move it to the top right as you have done for the other steps
image
- When user switches options from sandwich to smoothie (or vice versa), can we remove the "Step 1" portion in blue for sandwich as per below? It brings up an error prompt, but I think it doesn't make sense to leave the sandwich options there when user has decided to pick smoothie instead.
image


**UI Bug**
Next step and back buttons are buggy -
Once I click on the choice of bread and go to "next step", I can only see the "next step" button after I click on a protein.
However, when I click on a protein and click "back" to go to the bread page, no bread is selected and yet I am able to move on to the next step still (see screenshot below).
image
This bug can be repeated on other steps. It does not affect the final order summary (whatever was picked before still appears in the summary).

**Back To Selection**
- Does not save the choices I selected before, erases and forces user to restart the selection.
image

**Order Summary**
- Not selecting smoothie/not adding smoothie in the meal still includes it in the order summary
- Not selecting sandwich/not adding sandwich also includes the default into the order summary
Is this intended?
image

**Pickup Screen**
- Can we change the wording to "Pickup" instead of "Takeaway"?
- Not selecting any dates still allows for the pickup to be confirmed
image
- Can we have more pickup time options/wider variety?

**Comment by jumanahaseenn** [comment]
changes made per comments above - part 1 ( i will continue rest in part 2 shortly, working on itt)

- fixed the caps wordings & no more horizontal scroll-out
image
image

-concise descriptions 
image
image

**Comment by jumanahaseenn** [comment]
-	Shortened the description of products as suggested:
 
image
image

 
-	- an update is that customers are directly able to select upon pressing either sandwich or smoothie icon, dont need to go through another step to click customise to select options accordingly

-	Fixed pricing scams, now order summary would only display items which were selected by user and smoothie/sandwich would not appear unnecessarily when not selected for purchase. Both products would appear in summary only if customer chose to include smoothie in their meal. Below are 3 scenarios tested and pasted in images:
 
image
image

 
 
image



-	Next step button is placed at top right, just like other steps and it will appear regardless of an option is selected or not. This is for customers to toggle and browse through ingredients in each steps before they finalise. 

 
image


-	Now when user switches options from sandwich to smoothie (or vice versa), any existing steps will be removed and only smoothie options will pop up when user decide to pick smoothie instead. It will automatically direct to select “blend your smoothie button”. 

-	Now each selections are saved when you move forward to next step, when you click back, you will see what you had selected previously. Fixed the issue of not saving previous selection in prior steps.

-	Also added an alert prompt when users do not select the required number of ingredients to level up their sandwich :D

image


-	The back to selection button now saves the order when you choose to amend your ingredients. They will be brought to step1 of whichever item they wanted and they can choose to deselect and select different options.

-	Even if you initially did not include smoothie to your sandwich and decide to do so upon back to selection page, it will enable u to add the desired smoothie to your existing sandwich order.  They can also deselect and select a different option to modify.




-	Also added a feature to remove a product from summary if they no longer want to buy.

**Comment by jumanahaseenn** [comment]
hii, takeaway is also done with option to select variety dates from calendar form. but more update will be brought to make this better. for now kindly review this, thanks!
image

**Pull request merged**
