### PR TITLE
YX_Smart Inventory, Staff Profiling, Updates to OMS

### LINKED ISSUE #53: Page Skeleton for Smart Inventory

### PR DESCRIPTION
**Pull request by yyingxuann**
## Purpose
In this update I have pushed:
Updates based on PR for Smart Inventory page - Hardcoded Stock Level, Desired Quantity, New button with JS Modal to Notify Supplier via Email (supposed) on stock
- New staff profiling page - name, email
- Updated headers in all pages to include more pages + logout button

to be committed later on:
live date/time reflecting on current stock count in OMS page
extend hardcoded ingredient list to match what we have in DB 
further requests and changes from team

## Description of Changes
(see below)

## Screenshots/Recordings
new header + dropdown option for staff profile and logout (leads back to customer-home.html)
image

simple staff profiling
- further feedback and updates required
image

updated ITS page
- new column for minimum stock level
- new button for restock
- (not yet implemented) live date/time updates to show current stockcount, to check with @wilsongwee 
image
updated ITS page - restock button modal (intention is to send email to suppliers for stock)
image

(misc.) fixed path directory for headers

## Feedback Requested
Review of changes. 

## Testing Performed
Ran code locally.

## People to Notify
@wilsongwee 
@jumanahaseenn 
@wuguorongwuguorong 

## Checklist
- [] Feature or bug is completed.
- [x] Code is readable, comments and doc string written.
- [x] Conflicts with base branch resolved.

### CODE REVIEW

**Comment by jumanahaseenn** [comment]
helloo, thanks for the changes!

**Few points to ponder about:**

- should we rephrase the "minimum" to "Optimal stock range", as this is more firm is suggesting the desired quantity we need to run the business more efficiently

image

- can we add 3-4 more fields in the message - Quantity & Date of expected delivery, a supplier business email, cost price of the ingredient (this can be more realistic to show that we r purchasing something automatically with added price functionality with suppliers smoothly, but totally an optional field to add)

-  i could not send the message successfuly and received an error. We can have a prompt saying "Email sent successfully, for details please refer to the status in company portal for complete order details, etc "

image

**Comment by yyingxuann** [comment]
- Split ingredients table to Sandwich Ingredients and Smoothie Ingredients
- Updated headers design, table design
- Added a navigation header for Sandwich and Smoothie to jump to the tables easily
image
- Updated table column wording to "Optimal"
image
- Updated restock modal to include more fields
- Error prompt will appear when all fields are not filled
image
- Updated restock modal to only show fake success
image

[[bug not fixed]] i committed and accidentally bugged out the status colors. will recommit at a later time with update on this bug fix

**Comment by yyingxuann** [comment]
[[bug fixed]] fixed the status color bug, works now

**Comment by wilsongwee** [comment]
image

These column should be aligned

**Pull request merged**
